version: "3.7"

networks:
  default:
    external: true
    name: sagemaker-local

services:
  robomaker:
    image: awsdeepracercommunity/deepracer-robomaker:${DR_ROBOMAKER_IMAGE}
    command: ["/opt/files/devel.sh"]
    ports:
       - "5900:5900"
    environment:
      - DISPLAY
      - DR_WORLD_NAME
      - XAUTHORITY=/root/.Xauthority
      - QT_X11_NO_MITSHM=1
      - CUDA_VISIBLE_DEVICES
    volumes:
      - '../docker/files:/opt/files'
      - '../bundle:/opt/install'
      - '/tmp/.X11-unix/:/tmp/.X11-unix'
      - '${XAUTHORITY}:/root/.Xauthority'